version: "3.7"
services:
  backend:
    container_name: django
    build:
      context: /home/ubuntu/DROID_V2.1/deployment/jenkins/bastion
      dockerfile: Dockerfile
    env_file: /home/ubuntu/DROID_V2.1/.env
    command: sh /home/ubuntu/DROID_V2.1/deployment/jenkins/entrypointdjango.sh
    volumes:
      - /home/ubuntu/DROID_V2.1/:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/ubuntu/DROID_V2.1/deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/DROID_V2.1/deployment/files/staticfiles:/usr/share/nginx/html/static
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
  celery:
    container_name: Celery
    build:
      context: /home/ubuntu/DROID_V2.1/deployment/jenkins/bastion
      dockerfile: Dockerfile.celery
    command: sh /home/ubuntu/DROID_V2.1/deployment/jenkins/celery.sh
    env_file: /home/ubuntu/DROID_V2.1/deployment/.env
    volumes:
      - /home/ubuntu/DROID_V2.1/:/code
    restart: always
    depends_on:
      - backend
      - redis
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
