version: '2.1'
services:
  backend:
    container_name: django
    build:
      context: /var/lib/jenkins/workspace/Droid_v2
      dockerfile: deployment/jenkins/bastion/Dockerfile
    env_file: /var/lib/jenkins/workspace/Droid_v2/.env
    command: sh deployment/jenkins/bastion/entrypointdjango.sh
    image: django/backend
    volumes:
      - /var/lib/jenkins/workspace/Droid_v2:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /var/lib/jenkins/workspace/Droid_v2/deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/lib/jenkins/workspace/Droid_v2/files/staticfiles:/usr/share/nginx/html/static
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
  celery:
    container_name: Celery
    image: django/backend
    command: sh deployment/jenkins/bastion/celery.sh
    env_file: /var/lib/jenkins/workspace/Droid_v2/.env
    volumes:
      - /var/lib/jenkins/workspace/Droid_v2:/code
    restart: always
    depends_on:
      - backend
      - redis
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    