version: '2.1'
services:
  backend:
    container_name: django
    build:
      context: /home/ubuntu/DROID_V2.1
      dockerfile: deployment/jenkins/bastion/Dockerfile
    env_file: .env
    command: sh deployment/jenkins/entrypointdjango.sh
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/staticfiles:/usr/share/nginx/html/static
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
  celery:
    container_name: Celery
    build:
      context: /home/ubuntu/DROID_V2.1
      dockerfile: deployment/jenkins/bastion/Dockerfile.celery
    command: sh deployment/jenkins/celery.sh
    env_file: .env
    volumes:
      - ./:/code
    restart: always
    depends_on:
      - backend
      - redis
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
