version: "3.7"
services:
  backend:
    container_name: django
    build: ./deployment/jenkins/bastion
    env_file: .env
    command: sh deployment/jenkins/entrypointdjango.sh
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/api.default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.default.conf:/etc/nginx/sites-enabled/default.conf
      - ./backend/static:/usr/share/nginx/html/static
      - ./backend/media:/usr/share/nginx/html/media
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
  celery:
    container_name: Celery
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    command: sh entrypoint/entrycelerystagging.sh
    env_file: ./backend/.env
    volumes:
      - ./backend:/code
    restart: always
    depends_on:
      - backend
      - redis
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
