version: "3.7"
services:
  celery:
    container_name: Celery
    build:
      context: ./
      dockerfile: ./deployment/jenkins/pc1/Dockerfile
    command: sh deployment/jenkins/pc1/entrycelerylocal.sh
    env_file: .env
    volumes:
      - ./:/code
    restart: always

