# Generated by Django 3.1.4 on 2021-03-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0012_universerating_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('side', models.CharField(max_length=5)),
                ('asset_id', models.CharField(max_length=255)),
                ('client_order_id', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('subbmitted_at', models.DateTimeField()),
                ('filled_at', models.DateTimeField()),
                ('ticker_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.universe')),
            ],
            options={
                'db_table': 'transaction',
                'managed': True,
            },
        ),
    ]
