# Generated by Django 3.1.4 on 2021-03-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='filled_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
