# Generated by Django 3.1.4 on 2021-02-04 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0007_auto_20210202_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('market_status', models.BooleanField(default=True)),
                ('response', models.JSONField(blank=True, default=django.db.models.expressions.Value('null'), null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('logger_client_id', models.CharField(blank=True, max_length=300, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=300, null=True)),
                ('header', models.JSONField(blank=True, default=django.db.models.expressions.Value('null'), null=True)),
                ('body', models.JSONField(blank=True, default=django.db.models.expressions.Value('null'), null=True)),
                ('event', models.CharField(blank=True, max_length=250, null=True)),
                ('logger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger', to='Clients.clienttopstock')),
            ],
            options={
                'db_table': 'signal_logger',
                'managed': True,
            },
        ),
    ]
