# Generated by Django 3.1.4 on 2021-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggersignal',
            name='body',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='loggersignal',
            name='header',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='loggersignal',
            name='response',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
