# Generated by Django 3.1.4 on 2021-03-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0013_universe_ticker_symbol'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistic',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('option_type', models.TextField(blank=True, null=True)),
                ('bot_type', models.TextField(blank=True, null=True)),
                ('lookback', models.BigIntegerField(blank=True, null=True)),
                ('time_to_exp', models.FloatField(blank=True, null=True)),
                ('avg_days', models.FloatField(blank=True, null=True)),
                ('pct_profit', models.FloatField(blank=True, null=True)),
                ('pct_losses', models.FloatField(blank=True, null=True)),
                ('avg_profit', models.FloatField(blank=True, null=True)),
                ('avg_loss', models.FloatField(blank=True, null=True)),
                ('avg_return', models.FloatField(blank=True, null=True)),
                ('pct_max_profit', models.FloatField(blank=True, null=True)),
                ('pct_max_loss', models.FloatField(blank=True, null=True)),
                ('ann_avg_return', models.FloatField(blank=True, null=True)),
                ('ann_avg_return_bm', models.FloatField(blank=True, null=True)),
                ('avg_return_bm', models.FloatField(blank=True, null=True)),
                ('max_loss_bot', models.FloatField(blank=True, null=True)),
                ('max_loss_bm', models.FloatField(blank=True, null=True)),
                ('avg_days_max_profit', models.FloatField(blank=True, null=True)),
                ('avg_days_max_loss', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='bot_statistic_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'bot_statistic',
                'managed': True,
            },
        ),
    ]
