# Generated by Django 3.1.4 on 2021-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botoptiontype',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottype',
            name='bot_apps_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottype',
            name='bot_apps_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
