# Generated by Django 3.1.4 on 2021-03-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_auto_20210316_0813'),
        ('bot', '0004_botranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestBotRanking',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('bot_type', models.TextField(blank=True, null=True)),
                ('bot_option_type', models.DateField(blank=True, null=True)),
                ('time_to_exp', models.FloatField(blank=True, null=True)),
                ('time_to_exp_str', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('bot_id', models.ForeignKey(db_column='bot_id', on_delete=django.db.models.deletion.CASCADE, related_name='latest_bot_ranking_bot_id', to='bot.botoptiontype')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='latest_bot_ranking_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'latest_bot_ranking',
                'managed': True,
            },
        ),
    ]
