# Generated by Django 3.1.4 on 2021-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_latestbotranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='botoptiontype',
            name='bot_option_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
