# Generated by Django 3.1.4 on 2021-03-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_botoptiontype_bot_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestbotranking',
            name='bot_option_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
