# Generated by Django 3.1.4 on 2021-03-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210324_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botoptiontype',
            name='bot_option_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
