# Generated by Django 3.1.4 on 2021-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210324_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='botoptiontype',
            name='time_to_exp_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
