# Generated by Django 3.1.4 on 2021-03-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_botoptiontype_time_to_exp_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotRanking',
        ),
    ]
