# Generated by Django 3.1.4 on 2021-03-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_auto_20210316_0813'),
        ('bot', '0011_botranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestBotUpdate',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('spot_price', models.FloatField(blank=True, null=True)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('potential_max_loss', models.FloatField(blank=True, null=True)),
                ('targeted_profit', models.FloatField(blank=True, null=True)),
                ('bot_type', models.TextField(blank=True, null=True)),
                ('bot_option_type', models.TextField(blank=True, null=True)),
                ('time_to_exp', models.FloatField(blank=True, null=True)),
                ('time_to_exp_str', models.TextField(blank=True, null=True)),
                ('v0', models.FloatField(blank=True, null=True)),
                ('vol_t_003846', models.FloatField(blank=True, null=True)),
                ('vol_t_007692', models.FloatField(blank=True, null=True)),
                ('vol_t_008333', models.FloatField(blank=True, null=True)),
                ('vol_t_015384', models.FloatField(blank=True, null=True)),
                ('vol_t_016666', models.FloatField(blank=True, null=True)),
                ('vol_t_025', models.FloatField(blank=True, null=True)),
                ('vol_t_05', models.FloatField(blank=True, null=True)),
                ('classic_vol', models.FloatField(blank=True, null=True)),
                ('option_price', models.FloatField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('strike_2', models.FloatField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('rebate', models.FloatField(blank=True, null=True)),
                ('t', models.IntegerField(blank=True, null=True)),
                ('r', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('expiry_003846', models.DateField(blank=True, null=True)),
                ('expiry_007692', models.DateField(blank=True, null=True)),
                ('expiry_008333', models.DateField(blank=True, null=True)),
                ('expiry_015384', models.DateField(blank=True, null=True)),
                ('expiry_016666', models.DateField(blank=True, null=True)),
                ('expiry_025', models.DateField(blank=True, null=True)),
                ('expiry_05', models.DateField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('bot_id', models.ForeignKey(db_column='bot_id', on_delete=django.db.models.deletion.CASCADE, related_name='latest_bot_update_bot_id', to='bot.botoptiontype')),
                ('currency_code', models.ForeignKey(db_column='currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='latest_bot_update_currency_code', to='universe.currency')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='latest_bot_update_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'latest_bot_update',
                'managed': True,
            },
        ),
    ]
