# Generated by Django 3.1.4 on 2021-03-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_auto_20210316_0813'),
        ('bot', '0012_latestbotupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestVol',
            fields=[
                ('ticker', models.OneToOneField(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest_vol_ticker', serialize=False, to='universe.universe')),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('atm_volatility_spot', models.FloatField(blank=True, null=True)),
                ('atm_volatility_one_year', models.FloatField(blank=True, null=True)),
                ('atm_volatility_infinity', models.FloatField(blank=True, null=True)),
                ('slope', models.FloatField(blank=True, null=True)),
                ('deriv', models.FloatField(blank=True, null=True)),
                ('slope_inf', models.FloatField(blank=True, null=True)),
                ('deriv_inf', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'latest_vol',
                'managed': True,
            },
        ),
    ]
