# Generated by Django 3.1.4 on 2021-04-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_latestbotdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbacktest',
            name='bot_id',
            field=models.ForeignKey(db_column='bot_id', default='UNO_ITM_025', on_delete=django.db.models.deletion.CASCADE, related_name='lbot_backtest_bot_id', to='bot.botoptiontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botoptiontype',
            name='bot_type',
            field=models.ForeignKey(db_column='bot_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_option_type_bot_type', to='bot.bottype'),
        ),
    ]
