
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/DROID_V2.1
    runas: ubuntu
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: deployment/script/codedeploy/stop_server.sh
      runas: ubuntu
  BeforeInstall:
    - location: deployment/script/codedeploy/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: deployment/script/codedeploy/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: deployment/script/codedeploy/start_server.sh
      runas: ubuntu
  # AfterAllowTraffic:
  #   - location: deployment/script/codedeploy/start_server.sh
  #
