
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
    runas: ubuntu
hooks:
  BeforeInstall:
    - location: debug.sh
  AfterInstall:
    - location: deployment/scripts/after_install.sh
  ApplicationStart:
    - location: deployment/scripts/start_server.sh
  ApplicationStop:
    - location: debug.sh
  AfterAllowTraffic:
    - location: deployment/scripts/start_server.sh