
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/DROID_V2.1
    runas: ubuntu

    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - runas: ubuntu
    - location: deployment/script/codedeploy/stop_server.sh
  BeforeInstall:
    - runas: ubuntu
    - location: deployment/script/codedeploy/before_install.sh
  AfterInstall:
    - runas: ubuntu
    - location: deployment/script/codedeploy/after_install.sh
  ApplicationStart:
    - runas: ubuntu
    - location: deployment/script/codedeploy/start_server.sh
  # AfterAllowTraffic:
  #   - location: deployment/script/codedeploy/start_server.sh
  #