version: 0.2
artifacts:
    files:
    - '**/*'
    name: s3-to-s3-latest-build.zip
phases:
  install:
    commands:
      - echo "installing test dependencies"
      - pip install -r installer/requirements_test.txt
  pre_build:
    on-failure: ABORT
    commands:
      - echo "check DB Before running tests"
      - python manage.py createtestdb --settings=config.settings.production
  build:
    on-failure: ABORT
    commands:
        - pytest -s --ds=config.settings.prodtest
        - python manage.py testuserdeposit --settings=config.settings.production
        - python manage.py testuserdeposit --delete --settings=config.settings.production
        - echo "$CODEBUILD_BUILD_SUCCEEDING"
        - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
  post_build:
    commands:
      - echo test completed on `date`
      - echo create master image
      - python manage.py create_image -b master
