version: 0.2
artifacts:
    files:
    - '**/*'
    name: s3-to-s3-latest-build.zip
phases:
  install:
    commands:
      - echo "installing test dependencies"
      - pip install -r installer/requirements_test.txt
  pre_build:
    on-failure: ABORT
    commands:
      - echo "check DB Before running tests"
      - python manage.py createtestdb --settings=config.production
  build:
    on-failure: ABORT
    commands:
        - export DJANGO_SETTINGS_MODULE=config.production
        - pytest -s --ds=config.prodtest
        # - pytest -s
        - echo "$CODEBUILD_BUILD_SUCCEEDING"
        - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
  post_build:
    commands:
      - echo test completed on `date`
      - echo create master image
      - python manage.py create_image -b master
      # - docker run -v /var/run/docker.sock:/var/run/docker.sock
      # - docker version