version: 0.2
artifacts:
    files:
    - '**/*'
    name: s3-to-s3-latest-build.zip
phases:
  install:
    commands:
      - echo "skip installing test dependencies"
      # - pip install -r installer/requirements_test.txt
  pre_build:
    on-failure: ABORT
    commands:
      - echo "check DB Before running tests"
      - python manage.py send_slack_message -m 'preparing update'
      # - python manage.py createtestdb --settings=config.settings.production
    finally:
      - ./deployment/script/codebuild/beforetest.sh
  build:
    on-failure: ABORT
    commands:
        # - pytest -s --ds=config.settings.prodtest
        - echo "$CODEBUILD_BUILD_SUCCEEDING"
        - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
    finally:
        - ./deployment/script/codebuild/after_test.sh
  post_build:
    commands:
      - echo test completed on `date`
      - echo create master image
      - python manage.py create_image -b master
      - python manage.py send_slack_message -m 'preparing Blue/Green deploy' --settings=config.settings.production

