# Generated by Django 3.2.5 on 2021-08-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('order_uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('setup', models.JSONField(blank=True, default=dict, null=True)),
                ('order_type', models.CharField(blank=True, max_length=75, null=True)),
                ('placed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='review', max_length=10, null=True)),
                ('side', models.CharField(default='buy', max_length=10)),
                ('amount', models.FloatField()),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('is_init', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('performance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('fee_type', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'orders_fee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('position_uid', models.CharField(editable=False, max_length=500, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('investment_amount', models.FloatField(default=0)),
                ('max_loss_pct', models.FloatField(blank=True, null=True)),
                ('max_loss_price', models.FloatField(blank=True, null=True)),
                ('max_loss_amount', models.FloatField(blank=True, null=True)),
                ('target_profit_pct', models.FloatField(blank=True, null=True)),
                ('target_profit_price', models.FloatField(blank=True, null=True)),
                ('target_profit_amount', models.FloatField(blank=True, null=True)),
                ('bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=75, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('final_return', models.FloatField(blank=True, null=True)),
                ('final_pnl_amount', models.FloatField(blank=True, null=True)),
                ('current_inv_ret', models.FloatField(blank=True, null=True)),
                ('current_inv_amt', models.FloatField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('share_num', models.FloatField(blank=True, null=True)),
                ('current_returns', models.FloatField(blank=True, default=0, null=True)),
                ('current_values', models.FloatField(blank=True, default=0, null=True)),
                ('commision_fee', models.FloatField(blank=True, default=0, null=True)),
                ('commision_fee_sell', models.FloatField(blank=True, default=0, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(default=1)),
                ('bot_cash_dividend', models.FloatField(blank=True, default=0, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='ticker_ordered', to='universe.universe')),
            ],
            options={
                'db_table': 'orders_position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PositionPerformance',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('performance_uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('last_spot_price', models.FloatField(blank=True, null=True)),
                ('last_live_price', models.FloatField(blank=True, null=True)),
                ('current_pnl_ret', models.FloatField(blank=True, null=True)),
                ('current_pnl_amt', models.FloatField(blank=True, null=True)),
                ('current_bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('share_num', models.FloatField(blank=True, null=True)),
                ('current_investment_amount', models.FloatField(blank=True, null=True)),
                ('last_hedge_delta', models.FloatField(blank=True, null=True)),
                ('option_price', models.FloatField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('r', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('strike_2', models.FloatField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, null=True)),
                ('order_uid', models.ForeignKey(blank=True, db_column='order_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('position_uid', models.ForeignKey(db_column='position_uid', on_delete=django.db.models.deletion.CASCADE, related_name='order_position', to='orders.orderposition')),
            ],
            options={
                'db_table': 'orders_position_performance',
                'managed': True,
            },
        ),
    ]
