# Generated by Django 3.1.4 on 2021-04-12 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0016_universe_exchange_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPositon',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('investment_amount', models.FloatField()),
                ('market_value', models.FloatField()),
                ('pnl_percentage', models.FloatField()),
                ('pnl_value', models.FloatField()),
                ('use_bot', models.BooleanField(default=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bot', models.JSONField(blank=True, null=True)),
                ('entry_price', models.FloatField()),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('shares', models.FloatField()),
                ('is_live', models.BooleanField(default=True)),
                ('max_loss_pct', models.FloatField(blank=True, null=True)),
                ('max_loss_price', models.FloatField(blank=True, null=True)),
                ('max_loss_amount', models.FloatField(blank=True, null=True)),
                ('target_profit_pct', models.FloatField(blank=True, null=True)),
                ('target_profit_price', models.FloatField(blank=True, null=True)),
                ('target_profit_amount', models.FloatField(blank=True, null=True)),
                ('bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=75, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('final_return', models.FloatField(blank=True, null=True)),
                ('final_pnl_amount', models.FloatField(blank=True, null=True)),
                ('commision_fee_buy', models.FloatField(blank=True, default=0, null=True)),
                ('commision_fee_sell', models.FloatField(blank=True, default=0, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_symbol', to='universe.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_position', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('current_pnl_ret', models.FloatField(blank=True, null=True)),
                ('current_pnl_amt', models.FloatField(blank=True, null=True)),
                ('current_bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('share_num', models.FloatField(blank=True, null=True)),
                ('current_investment_amount', models.FloatField(blank=True, null=True)),
                ('last_hedge_delta', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(max_length=5)),
                ('filled_avg_price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('option_price', models.FloatField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('r', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('strike_2', models.FloatField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_position', to='orders.orderpositon')),
            ],
            options={
                'db_table': 'order_transaction_history',
                'managed': True,
            },
        ),
    ]
