# Generated by Django 3.1.4 on 2021-04-13 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0016_universe_exchange_code'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('last_spot_price', models.FloatField(blank=True, null=True)),
                ('last_live_price', models.FloatField(blank=True, null=True)),
                ('current_pnl_ret', models.FloatField(blank=True, null=True)),
                ('current_pnl_amt', models.FloatField(blank=True, null=True)),
                ('current_bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('share_num', models.FloatField(blank=True, null=True)),
                ('current_investment_amount', models.FloatField(blank=True, null=True)),
                ('last_hedge_delta', models.FloatField(blank=True, null=True)),
                ('option_price', models.FloatField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('r', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('strike_2', models.FloatField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_positon_performance',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='orderpositon',
            old_name='commision_fee_buy',
            new_name='commision_fee',
        ),
        migrations.RenameField(
            model_name='orderpositon',
            old_name='avg_price',
            new_name='current_inv_amt',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='market_value',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='pnl_percentage',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='pnl_value',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='orderpositon',
            name='use_bot',
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='current_inv_ret',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='current_returns',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='current_values',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='ric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticker_ordered', to='universe.universe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='share_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpositon',
            name='spot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderpositon',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderpositon',
            name='investment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderpositon',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderpositon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_postion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.AddField(
            model_name='positionperformance',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_position', to='orders.orderpositon'),
        ),
    ]
