# Generated by Django 3.2.5 on 2021-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionperformance',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
