# Generated by Django 3.1.4 on 2021-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210715_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='bot_cash_dividend',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
