# Generated by Django 3.1.4 on 2021-04-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210413_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpositon',
            old_name='ric',
            new_name='symbol',
        ),
    ]
