# Generated by Django 3.1.4 on 2021-04-13 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20210413_0629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPositon',
            new_name='OrderPosition',
        ),
    ]
