# Generated by Django 3.2.5 on 2021-08-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_historicalorderposition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalorderposition',
            table='order_position_history',
        ),
    ]
