# Generated by Django 3.1.4 on 2021-04-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0016_universe_exchange_code'),
        ('orders', '0005_auto_20210413_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('setup', models.JSONField(blank=True, default=dict, null=True)),
                ('order_type', models.CharField(blank=True, max_length=75, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField()),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('is_init', models.BooleanField(default=True)),
                ('use_hedge', models.BooleanField(default=False)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_order', to='universe.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
