# Generated by Django 3.2.5 on 2021-08-20 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0004_auto_20210819_0640'),
        ('orders', '0005_alter_historicalorderposition_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('order_uid', models.UUIDField(db_index=True, editable=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('setup', models.JSONField(blank=True, default=dict, null=True)),
                ('order_type', models.CharField(blank=True, max_length=75, null=True)),
                ('placed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='review', max_length=10, null=True)),
                ('side', models.CharField(default='buy', max_length=10)),
                ('amount', models.FloatField()),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('order_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('is_init', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('performance_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='universe.universe')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'db_table': 'order_change_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
