# Generated by Django 3.2.5 on 2021-08-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='margin',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='margin',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
