# Generated by Django 3.2.5 on 2021-10-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210826_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderposition',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='positionperformance',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
