# Generated by Django 3.2.5 on 2021-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211012_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderposition',
            name='current_inv_amt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorderposition',
            name='current_inv_ret',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorderposition',
            name='share_num',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='current_inv_amt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='current_inv_ret',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='share_num',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
