# Generated by Django 3.1.4 on 2021-04-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210413_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='use_hedge',
        ),
    ]
