# Generated by Django 3.2.5 on 2021-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211027_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Features',
                'managed': True,
            },
        ),
    ]
