# Generated by Django 3.1.4 on 2021-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(default='buy', max_length=10),
        ),
    ]
