# Generated by Django 3.1.4 on 2021-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_positionperformance_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
