# Generated by Django 3.1.4 on 2021-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_signal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='vol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
