# Generated by Django 3.1.4 on 2021-04-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_orderposition_vol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='uid',
            new_name='order_uid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='signal_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='orderposition',
            old_name='uid',
            new_name='position_uid',
        ),
        migrations.RemoveField(
            model_name='positionperformance',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='positionperformance',
            name='order_id',
        ),
        migrations.AddField(
            model_name='positionperformance',
            name='order_uid',
            field=models.ForeignKey(blank=True, db_column='order_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='review', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='symbol_order', to='universe.universe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='symbol',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='ticker_ordered', to='universe.universe'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positionperformance',
            name='position',
            field=models.ForeignKey(db_column='position_uid', on_delete=django.db.models.deletion.CASCADE, related_name='order_position', to='orders.orderposition'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderposition',
            table='orders_position',
        ),
        migrations.AlterModelTable(
            name='positionperformance',
            table='orders_position_performance',
        ),
    ]
