# Generated by Django 3.1.4 on 2021-04-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210416_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='p_id',
            new_name='performance_uid',
        ),
        migrations.RemoveField(
            model_name='positionperformance',
            name='id',
        ),
        migrations.AddField(
            model_name='positionperformance',
            name='performance_uid',
            field=models.CharField(default=4312313, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
