# Generated by Django 3.1.4 on 2021-04-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210416_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionperformance',
            name='performance_uid',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
