# Generated by Django 3.1.4 on 2021-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210416_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderposition',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='orderposition',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='positionperformance',
            old_name='position',
            new_name='position_uid',
        ),
    ]
