# Generated by Django 3.1.4 on 2021-04-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210416_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='positionperformance',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
