# Generated by Django 3.1.4 on 2021-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210420_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
