# Generated by Django 3.1.4 on 2021-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='position_uid',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
