# Generated by Django 3.1.4 on 2021-05-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210504_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('fee_type', models.TextField(blank=True, null=True)),
                ('commissions', models.FloatField(default=0)),
                ('stamp_duty', models.FloatField(default=0)),
                ('total_fee', models.FloatField(default=0)),
                ('order_uid', models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.CASCADE, related_name='orders_fee_orders', to='orders.order')),
            ],
            options={
                'db_table': 'orders_fee',
                'managed': True,
            },
        ),
    ]
