# Generated by Django 3.1.4 on 2021-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='margin',
            field=models.FloatField(default=1),
        ),
    ]
