# Generated by Django 3.1.4 on 2021-05-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderposition_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='margin_value',
            field=models.FloatField(default=1),
        ),
    ]
