# Generated by Django 3.1.4 on 2021-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_orderposition_margin_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='investment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='margin_value',
            field=models.FloatField(default=0),
        ),
    ]
