# Generated by Django 3.1.4 on 2021-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20210509_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionperformance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
