# Generated by Django 3.1.4 on 2021-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_positionperformance_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfee',
            old_name='commissions',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='orderfee',
            name='stamp_duty',
        ),
        migrations.RemoveField(
            model_name='orderfee',
            name='total_fee',
        ),
    ]
