# Generated by Django 3.1.4 on 2021-05-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210510_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='margin_value',
        ),
        migrations.RemoveField(
            model_name='positionperformance',
            name='margin_balance',
        ),
    ]
