# Generated by Django 3.1.4 on 2021-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20210510_1216'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='positionperformance',
            index=models.Index(fields=['created', 'position_uid', 'order_uid'], name='orders_posi_created_641a2f_idx'),
        ),
    ]
