# Generated by Django 3.1.4 on 2021-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210622_0901'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderposition',
            index=models.Index(fields=['user_id', 'ticker'], name='orders_posi_user_id_729cf6_idx'),
        ),
    ]
