# Generated by Django 3.1.4 on 2021-07-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0010_remove_universe_yolo'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeLatestPriceHistory',
            fields=[
                ('hedge_uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('latest_price_change', models.FloatField(blank=True, null=True)),
                ('intraday_time', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('latest_price', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='hedge_latest_price_ticker_history', to='universe.universe')),
            ],
            options={
                'db_table': 'hedge_latest_price_history',
                'managed': True,
            },
        ),
    ]
