# Generated by Django 3.1.4 on 2021-06-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafundamentalscore',
            name='environment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafundamentalscore',
            name='goverment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafundamentalscore',
            name='social',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
