# Generated by Django 3.1.4 on 2021-02-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_auto_20210129_1023'),
        ('master', '0002_delete_mastertac'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTac',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('total_return_index', models.FloatField(blank=True, null=True)),
                ('tri_adj_open', models.FloatField(blank=True, null=True)),
                ('tri_adj_high', models.FloatField(blank=True, null=True)),
                ('tri_adj_low', models.FloatField(blank=True, null=True)),
                ('tri_adj_close', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('fast_k', models.FloatField(blank=True, null=True)),
                ('fast_d', models.FloatField(blank=True, null=True)),
                ('currency_code', models.ForeignKey(db_column='currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='master_tac_currency_code', to='universe.currency')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='master_tac_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'master_tac',
                'managed': True,
            },
        ),
    ]
