# Generated by Django 3.1.4 on 2021-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_hedgelatestpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgelatestpricehistory',
            name='types',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
