# Generated by Django 3.2.5 on 2021-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210824_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestprice',
            name='latest_net_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
