# Generated by Django 3.1.4 on 2021-03-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_mastertac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavolsurfaceinferred',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='DataVolSurface',
        ),
        migrations.DeleteModel(
            name='DataVolSurfaceInferred',
        ),
    ]
