# Generated by Django 3.1.4 on 2021-07-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210702_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldscopesummary',
            name='fn_5575',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
