# Generated by Django 3.1.4 on 2021-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210303_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertac',
            name='day_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
