# Generated by Django 3.2.5 on 2021-08-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210824_0751'),
        ('master', '0004_latestprice_latest_net_change'),
    ]

    operations = [
    ]
