# Generated by Django 3.1.4 on 2021-03-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_universerating_updated'),
        ('master', '0005_mastertac_day_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fred',
            fields=[
                ('trading_day', models.DateField(primary_key=True, serialize=False)),
                ('data', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_fred',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('period_end', models.DateField(primary_key=True, serialize=False)),
                ('chgdp', models.FloatField(blank=True, null=True)),
                ('jpgdp', models.FloatField(blank=True, null=True)),
                ('usgdp', models.FloatField(blank=True, null=True)),
                ('emgdp', models.FloatField(blank=True, null=True)),
                ('emibor3', models.FloatField(blank=True, null=True)),
                ('emgbond', models.FloatField(blank=True, null=True)),
                ('chgbond', models.FloatField(blank=True, null=True)),
                ('usinter3', models.FloatField(blank=True, null=True)),
                ('usgbill3', models.FloatField(blank=True, null=True)),
                ('jpmshort', models.FloatField(blank=True, null=True)),
                ('fred_data', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_macro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MacroMonthly',
            fields=[
                ('trading_day', models.DateField(primary_key=True, serialize=False)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('chgdp', models.FloatField(blank=True, null=True)),
                ('jpgdp', models.FloatField(blank=True, null=True)),
                ('usgdp', models.FloatField(blank=True, null=True)),
                ('emgdp', models.FloatField(blank=True, null=True)),
                ('emibor3', models.FloatField(blank=True, null=True)),
                ('emgbond', models.FloatField(blank=True, null=True)),
                ('chgbond', models.FloatField(blank=True, null=True)),
                ('usinter3', models.FloatField(blank=True, null=True)),
                ('usgbill3', models.FloatField(blank=True, null=True)),
                ('jpmshort', models.FloatField(blank=True, null=True)),
                ('fred_data', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_macro_monthly',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IbesMonthly',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('period_end', models.FloatField(blank=True, null=True)),
                ('eps1fd12', models.FloatField(blank=True, null=True)),
                ('eps1tr12', models.FloatField(blank=True, null=True)),
                ('cap1fd12', models.FloatField(blank=True, null=True)),
                ('epsi1md', models.FloatField(blank=True, null=True)),
                ('i0eps', models.FloatField(blank=True, null=True)),
                ('ebd1fd12', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='data_ibes_monthly_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'data_ibes_monthly',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ibes',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('epsi1md', models.FloatField(blank=True, null=True)),
                ('i0eps', models.FloatField(blank=True, null=True)),
                ('cap1fd12', models.FloatField(blank=True, null=True)),
                ('ebd1fd12', models.FloatField(blank=True, null=True)),
                ('eps1fd12', models.FloatField(blank=True, null=True)),
                ('eps1tr12', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='data_ibes_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'data_ibes',
                'managed': True,
            },
        ),
    ]
