# Generated by Django 3.2.5 on 2021-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_merge_20210825_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafundamentalscore',
            old_name='total_asset',
            new_name='assets_1yr',
        ),
        migrations.AddField(
            model_name='datafundamentalscore',
            name='mkt_cap_ye',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
