# Generated by Django 3.1.4 on 2021-03-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_fred_ibes_ibesmonthly_macro_macromonthly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IbesMonthly',
        ),
    ]
