# Generated by Django 3.2.5 on 2021-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20210831_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldscopesummary',
            name='fn_2003',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
