# Generated by Django 3.1.4 on 2021-03-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_universerating_updated'),
        ('master', '0007_delete_ibesmonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbesMonthly',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('eps1fd12', models.FloatField(blank=True, null=True)),
                ('eps1tr12', models.FloatField(blank=True, null=True)),
                ('cap1fd12', models.FloatField(blank=True, null=True)),
                ('epsi1md', models.FloatField(blank=True, null=True)),
                ('i0eps', models.FloatField(blank=True, null=True)),
                ('ebd1fd12', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='data_ibes_monthly_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'data_ibes_monthly',
                'managed': True,
            },
        ),
    ]
