# Generated by Django 3.1.4 on 2021-03-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_universerating_updated'),
        ('master', '0008_ibesmonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPrice',
            fields=[
                ('ticker', models.OneToOneField(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest_price_ticker', serialize=False, to='universe.universe')),
                ('classic_vol', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('intraday_date', models.DateField(blank=True, null=True)),
                ('intraday_ask', models.FloatField(blank=True, null=True)),
                ('intraday_bid', models.FloatField(blank=True, null=True)),
                ('latest_price_change', models.FloatField(blank=True, null=True)),
                ('intraday_time', models.TextField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('capital_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'latest_price',
                'managed': True,
            },
        ),
    ]
