# Generated by Django 3.1.4 on 2021-03-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_auto_20210316_0813'),
        ('master', '0009_latestprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldscopeSummary',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('frequency_number', models.IntegerField(blank=True, null=True)),
                ('fiscal_quarter_end', models.IntegerField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('fn_2001', models.FloatField(blank=True, null=True)),
                ('fn_2101', models.FloatField(blank=True, null=True)),
                ('fn_2201', models.FloatField(blank=True, null=True)),
                ('fn_2501', models.FloatField(blank=True, null=True)),
                ('fn_3101', models.FloatField(blank=True, null=True)),
                ('fn_5085', models.FloatField(blank=True, null=True)),
                ('fn_8001', models.FloatField(blank=True, null=True)),
                ('fn_18100', models.FloatField(blank=True, null=True)),
                ('fn_18158', models.FloatField(blank=True, null=True)),
                ('fn_18199', models.FloatField(blank=True, null=True)),
                ('fn_18262', models.FloatField(blank=True, null=True)),
                ('fn_18263', models.FloatField(blank=True, null=True)),
                ('fn_18264', models.FloatField(blank=True, null=True)),
                ('fn_18265', models.FloatField(blank=True, null=True)),
                ('fn_18266', models.FloatField(blank=True, null=True)),
                ('fn_18267', models.FloatField(blank=True, null=True)),
                ('fn_18269', models.FloatField(blank=True, null=True)),
                ('fn_18304', models.FloatField(blank=True, null=True)),
                ('fn_18308', models.FloatField(blank=True, null=True)),
                ('fn_18309', models.FloatField(blank=True, null=True)),
                ('fn_18310', models.FloatField(blank=True, null=True)),
                ('fn_18311', models.FloatField(blank=True, null=True)),
                ('fn_18312', models.FloatField(blank=True, null=True)),
                ('fn_18313', models.FloatField(blank=True, null=True)),
                ('fn_3501', models.FloatField(blank=True, null=True)),
                ('fn_3255', models.FloatField(blank=True, null=True)),
                ('fn_18271', models.FloatField(blank=True, null=True)),
                ('fn_2999', models.FloatField(blank=True, null=True)),
                ('fn_5192', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='data_worldscope_summary_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'data_worldscope_summary',
                'managed': True,
            },
        ),
    ]
