# Generated by Django 3.1.4 on 2021-03-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_worldscopesummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldscopesummary',
            old_name='identifier',
            new_name='worldscope_identifier',
        ),
    ]
