# Generated by Django 3.1.4 on 2021-07-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_presence', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPresence',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('channels_presence.room',),
        ),
    ]
