# Generated by Django 3.2.5 on 2021-07-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_hedgelogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hedgelogger',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelTable(
            name='hedgelogger',
            table='log_hedge_position',
        ),
    ]
