# Generated by Django 3.2.5 on 2021-07-28 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderposition_bot_cash_dividend'),
        ('services', '0004_auto_20210728_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgelogger',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hedgelogger',
            unique_together={('order_uid', 'log_type', 'date')},
        ),
    ]
