# Generated by Django 3.2.5 on 2021-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderposition_bot_cash_dividend'),
        ('services', '0005_auto_20210728_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgelogger',
            old_name='order_uid',
            new_name='position_uid',
        ),
        migrations.AlterField(
            model_name='hedgelogger',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hedgelogger',
            unique_together={('position_uid', 'log_type', 'date')},
        ),
    ]
