FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN mkdir installer deployment
COPY ./installer /installer/
COPY ./deployment /deployment/
# WORKDIR code/
RUN installer/requirement.sh
# RUN pip install -r installer/requirements_test.txt

# COPY . /code/
