# Generated by Django 3.2.5 on 2021-08-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('client_uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_credentials', models.JSONField(blank=True, null=True)),
                ('commissions_buy', models.FloatField(blank=True, null=True)),
                ('commissions_sell', models.FloatField(blank=True, null=True)),
                ('commissions_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientTopStock',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('has_position', models.BooleanField(default=False)),
                ('position_uid', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('bot_id', models.CharField(blank=True, max_length=80, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=80, null=True)),
                ('capital', models.CharField(blank=True, max_length=80, null=True)),
                ('bot', models.CharField(blank=True, max_length=80, null=True)),
                ('week_of_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Client Generated Top stock',
                'db_table': 'client_top_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UniverseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'universe_client',
                'get_latest_by': 'created',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('use_currency', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('stamp_duty_buy', models.FloatField(blank=True, null=True)),
                ('stamp_duty_sell', models.FloatField(blank=True, null=True)),
                ('stamp_duty_type', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='client_related', to='Clients.client')),
                ('currency_code', models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_currency', to='universe.currency')),
            ],
            options={
                'db_table': 'user_clients',
                'managed': True,
            },
        ),
    ]
