# Generated by Django 3.1.4 on 2021-01-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('created', models.DateField(editable=False)),
                ('updated', models.DateField(editable=False)),
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_related', to='universe.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateField(editable=False)),
                ('updated', models.DateField(editable=False)),
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_base_commision', models.FloatField(blank=True, null=True)),
                ('use_currency', models.BooleanField(default=True)),
                ('client_credentials', models.JSONField(blank=True, null=True)),
                ('client_base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_currency', to='universe.currency')),
                ('client_universe', models.ManyToManyField(related_name='client_currency', to='universe.Universe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
