# Generated by Django 3.1.4 on 2021-01-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_country'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userclient',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_universe',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='userclient',
            table='user_clients',
        ),
        migrations.CreateModel(
            name='UniverseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('updated', models.DateField(editable=False)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, related_name='universe_client', to='Clients.client')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='client_universe', to='universe.universe')),
            ],
            options={
                'db_table': 'universe_client',
                'get_latest_by': 'created',
                'managed': True,
                'unique_together': {('ticker', 'client')},
            },
        ),
    ]
