# Generated by Django 3.1.4 on 2021-07-15 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universeclient',
            name='client',
            field=models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='universe_client', to='Clients.client'),
        ),
        migrations.AddField(
            model_name='universeclient',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='client_universe', to='universe.universe'),
        ),
        migrations.AddField(
            model_name='clienttopstock',
            name='client',
            field=models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='client_top_stock', to='Clients.client'),
        ),
        migrations.AddField(
            model_name='clienttopstock',
            name='currency_code',
            field=models.ForeignKey(db_column='currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='topstock_currency', to='universe.currency'),
        ),
        migrations.AddField(
            model_name='clienttopstock',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='universe_top_stock', to='universe.universe'),
        ),
        migrations.AlterUniqueTogether(
            name='universeclient',
            unique_together={('ticker', 'client')},
        ),
    ]
