# Generated by Django 3.1.4 on 2021-02-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_auto_20210129_1023'),
        ('Clients', '0006_auto_20210129_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='universeclient',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='universeclient',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.CreateModel(
            name='ClientTopStock',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('use_signal', models.BooleanField(default=False)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('has_order', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('current_status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Completed', 'Completed')], default='Inactive', max_length=25)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(max_length=50)),
                ('last_closing_price', models.FloatField(blank=True, null=True)),
                ('investment_amount', models.FloatField(blank=True, null=True)),
                ('vol_t', models.FloatField(blank=True, null=True)),
                ('max_loss_pct', models.FloatField(blank=True, null=True)),
                ('max_loss_price', models.FloatField(blank=True, null=True)),
                ('max_loss_amount', models.FloatField(blank=True, null=True)),
                ('target_profit_pct', models.FloatField(blank=True, null=True)),
                ('target_profit_price', models.FloatField(blank=True, null=True)),
                ('target_profit_amount', models.FloatField(blank=True, null=True)),
                ('execution_price', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, related_name='client_top_stock', to='Clients.client')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='universe_top_stock', to='universe.universe')),
            ],
            options={
                'verbose_name_plural': 'Client Generated Top stock',
                'db_table': 'client_top_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientBotPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('last_live_price', models.FloatField(blank=True, null=True)),
                ('current_pnl_ret', models.FloatField(blank=True, null=True)),
                ('current_pnl_amt', models.FloatField(blank=True, null=True)),
                ('current_bot_cash_balance', models.FloatField(blank=True, null=True)),
                ('share', models.FloatField(blank=True, null=True)),
                ('current_investment_amount', models.FloatField(blank=True, null=True)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('last_hedge_delta', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_perfomance', to='Clients.clienttopstock')),
            ],
            options={
                'verbose_name_plural': 'Client Bot History',
                'db_table': 'client_bot_history',
                'managed': True,
            },
        ),
    ]
