# Generated by Django 3.1.4 on 2021-04-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0007_auto_20210202_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uid',
            new_name='client_uid',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='execution_price',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='last_closing_price',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='max_loss_amount',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='max_loss_pct',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='max_loss_price',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='target_profit_amount',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='target_profit_pct',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='target_profit_price',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='use_signal',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='vol_t',
        ),
        migrations.AlterField(
            model_name='clienttopstock',
            name='client',
            field=models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='client_top_stock', to='Clients.client'),
        ),
        migrations.AlterField(
            model_name='universeclient',
            name='client',
            field=models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='universe_client', to='Clients.client'),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='client',
            field=models.ForeignKey(db_column='client_uid', on_delete=django.db.models.deletion.CASCADE, related_name='client_related', to='Clients.client'),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClientBotPerformance',
        ),
    ]
