# Generated by Django 3.1.4 on 2021-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        ('Clients', '0008_auto_20210416_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_base_currency',
            field=models.ForeignKey(db_column='currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='client_currency', to='universe.currency'),
        ),
    ]
