# Generated by Django 3.1.4 on 2021-04-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_auto_20210420_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttopstock',
            old_name='has_order',
            new_name='has_position',
        ),
        migrations.RenameField(
            model_name='clienttopstock',
            old_name='order_number',
            new_name='position_uid',
        ),
        migrations.RemoveField(
            model_name='clienttopstock',
            name='current_status',
        ),
    ]
