# Generated by Django 3.1.4 on 2021-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_auto_20210420_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttopstock',
            name='event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
