# Generated by Django 3.1.4 on 2021-04-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        ('Clients', '0013_clienttopstock_bot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_base_currency',
            new_name='currency_code',
        ),
        migrations.AddField(
            model_name='clienttopstock',
            name='currency_code',
            field=models.ForeignKey(db_column='currency_code', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topstock_currency', to='universe.currency'),
            preserve_default=False,
        ),
    ]
