# Generated by Django 3.1.4 on 2021-04-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        ('Clients', '0014_auto_20210423_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_base_commision',
        ),
        migrations.RemoveField(
            model_name='client',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='use_currency',
        ),
        migrations.AddField(
            model_name='userclient',
            name='currency_code',
            field=models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_currency', to='universe.currency'),
        ),
        migrations.AddField(
            model_name='userclient',
            name='use_currency',
            field=models.BooleanField(default=True),
        ),
    ]
