# Generated by Django 3.1.4 on 2021-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0016_auto_20210426_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttopstock',
            name='srevice_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
