# Generated by Django 3.1.4 on 2021-04-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0017_clienttopstock_srevice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttopstock',
            old_name='service_type',
            new_name='service_type',
        ),
    ]
