# Generated by Django 3.1.4 on 2021-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0017_clienttopstock_srevice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttopstock',
            old_name='srevice_type',
            new_name='capital',
        ),
        migrations.AddField(
            model_name='clienttopstock',
            name='service_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
