# Generated by Django 3.1.4 on 2021-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0018_auto_20210426_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttopstock',
            name='capital',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
