# Generated by Django 3.1.4 on 2021-04-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0018_auto_20210426_0908'),
        ('Clients', '0019_clienttopstock_capital'),
    ]

    operations = [
    ]
