# Generated by Django 3.1.4 on 2021-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0020_merge_20210427_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttopstock',
            name='bot',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
