# Generated by Django 3.1.4 on 2021-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0021_clienttopstock_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commissions_buy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='commissions_sell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='commissions_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='stamp_duty_buy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='stamp_duty_sell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='stamp_duty_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
