# Generated by Django 3.1.4 on 2021-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0023_clienttopstock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttopstock',
            name='week_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
