# Generated by Django 3.1.4 on 2021-06-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('country', models.CharField(max_length=128, unique=True)),
                ('censored_words', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'survey_censored_words',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('device_id', models.CharField(max_length=128)),
                ('likes_on', models.JSONField(default=dict)),
                ('location', models.CharField(default='Indonesia', max_length=128)),
            ],
            options={
                'db_table': 'survey_devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('investor_category', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'survey_investor_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('email', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('answer', models.JSONField(default=dict)),
                ('read_policy', models.BooleanField()),
                ('devices', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='survey.devices')),
                ('investor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.investortypes')),
            ],
            options={
                'db_table': 'survey_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('total_like', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.devices')),
            ],
            options={
                'db_table': 'survey_forum_post',
                'managed': True,
            },
        ),
    ]
