# Generated by Django 3.1.4 on 2021-02-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('device_id', models.CharField(max_length=128)),
                ('likes_on', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvestorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('investor_category', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'investor_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('email', models.CharField(max_length=128)),
                ('answer', models.JSONField(default=dict)),
                ('read_policy', models.BooleanField()),
                ('investor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.investortypes')),
            ],
            options={
                'db_table': 'survey_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('total_like', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.devices')),
            ],
            options={
                'db_table': 'fourm_post',
                'managed': True,
            },
        ),
    ]
