# Generated by Django 3.1.4 on 2021-02-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forumpost',
            table='forum_post',
        ),
    ]
