# Generated by Django 3.1.4 on 2021-02-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210224_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='location',
            field=models.CharField(default='Indonesia', max_length=128),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='devices',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='survey.devices'),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
