# Generated by Django 3.1.4 on 2021-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210225_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('country', models.CharField(max_length=128, unique=True)),
                ('censored_words', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'censored_words',
                'managed': True,
            },
        ),
    ]
