# Generated by Django 3.1.4 on 2021-03-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_censoredwords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='censoredwords',
            table='survey_censored_words',
        ),
        migrations.AlterModelTable(
            name='devices',
            table='survey_devices',
        ),
        migrations.AlterModelTable(
            name='forumpost',
            table='survey_forum_post',
        ),
        migrations.AlterModelTable(
            name='investortypes',
            table='survey_investor_types',
        ),
    ]
