# Generated by Django 3.1.4 on 2021-04-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210318_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censoredwords',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='investortypes',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
