# Generated by Django 3.1.4 on 2021-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'universe_hot',
            },
        ),
    ]
