# Generated by Django 3.1.4 on 2021-01-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='universeconsolidated',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='universeconsolidated',
            name='source_id',
            field=models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universe_source_id', to='universe.source'),
        ),
    ]
