# Generated by Django 3.2.5 on 2021-08-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemarket',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangemarket',
            name='until_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
