# Generated by Django 3.1.4 on 2021-06-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universeratinghistory',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='ai_score2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='esg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='momentum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='technical',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universeratinghistory',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='universe_rating_history_ticker', to='universe.universe'),
        ),
        migrations.CreateModel(
            name='UniverseRatingDetailHistory',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('earnings_yield_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('earnings_yield_minmax_industry', models.FloatField(blank=True, null=True)),
                ('book_to_price_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('book_to_price_minmax_industry', models.FloatField(blank=True, null=True)),
                ('ebitda_to_ev_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('ebitda_to_ev_minmax_industry', models.FloatField(blank=True, null=True)),
                ('sales_to_price_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('sales_to_price_minmax_industry', models.FloatField(blank=True, null=True)),
                ('roic_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('roic_minmax_industry', models.FloatField(blank=True, null=True)),
                ('roe_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('roe_minmax_industry', models.FloatField(blank=True, null=True)),
                ('cf_to_price_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('cf_to_price_minmax_industry', models.FloatField(blank=True, null=True)),
                ('eps_growth_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('eps_growth_minmax_industry', models.FloatField(blank=True, null=True)),
                ('fwd_bps_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('fwd_bps_minmax_industry', models.FloatField(blank=True, null=True)),
                ('fwd_ebitda_to_ev_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('fwd_ebitda_to_ev_minmax_industry', models.FloatField(blank=True, null=True)),
                ('fwd_ey_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('fwd_ey_minmax_industry', models.FloatField(blank=True, null=True)),
                ('fwd_sales_to_price_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('fwd_sales_to_price_minmax_industry', models.FloatField(blank=True, null=True)),
                ('fwd_roic_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('fwd_roic_minmax_industry', models.FloatField(blank=True, null=True)),
                ('earnings_pred_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('earnings_pred_minmax_industry', models.FloatField(blank=True, null=True)),
                ('tri_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('tri_minmax_industry', models.FloatField(blank=True, null=True)),
                ('environment_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('social_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('goverment_minmax_currency_code', models.FloatField(blank=True, null=True)),
                ('environment_minmax_industry_code', models.FloatField(blank=True, null=True)),
                ('social_minmax_industry_code', models.FloatField(blank=True, null=True)),
                ('goverment_minmax_industry_code', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='universe_rating_detail_history_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'universe_rating_detail_history',
                'managed': True,
            },
        ),
    ]
