# Generated by Django 3.1.4 on 2021-01-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.TextField(primary_key=True, serialize=False)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('ds_country_code', models.TextField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('currency_code', models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_currency_code', to='universe.currency')),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
    ]
