# Generated by Django 3.1.4 on 2021-01-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='has_isin',
            field=models.BooleanField(default=False),
        ),
    ]
