# Generated by Django 3.1.4 on 2021-01-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='universeconsolidated',
            name='permid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
