# Generated by Django 3.1.4 on 2021-07-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_auto_20210715_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='free_cash_flow2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
