# Generated by Django 3.1.4 on 2021-07-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_universe_free_cash_flow2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='free_cash_flow2',
        ),
    ]
