# Generated by Django 3.1.4 on 2021-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_auto_20210630_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='ebitda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='ev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='free_cash_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='pe_forecast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='revenue_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='wk52_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='wk52_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
