# Generated by Django 3.1.4 on 2021-07-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_auto_20210715_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='ebitda',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='ev',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='free_cash_flow',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='pb',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='pe_forecast',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='revenue_per_share',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='wk52_high',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='wk52_low',
        ),
    ]
