# Generated by Django 3.1.4 on 2021-01-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_universeconsolidated_permid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
