# Generated by Django 3.2.5 on 2021-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_auto_20210810_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='universerating',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universerating',
            name='ai_score2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
