# Generated by Django 3.2.5 on 2021-09-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_auto_20210819_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseHotness',
            fields=[
                ('ticker', models.OneToOneField(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='universe_hotness_ticker', serialize=False, to='universe.universe')),
                ('trading_day', models.DateField()),
                ('volume_rate_z', models.FloatField()),
            ],
            options={
                'db_table': 'universe_hotness',
                'managed': True,
            },
        ),
    ]
