# Generated by Django 3.1.4 on 2021-01-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_auto_20210129_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='consolidated_ticker',
            field=models.ForeignKey(blank=True, db_column='consolidated_ticker', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universe_consolidated', to='universe.universe'),
        ),
    ]
