# Generated by Django 3.1.4 on 2021-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_auto_20210715_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='revenue_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
