# Generated by Django 3.1.4 on 2021-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_auto_20210702_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='Error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
