# Generated by Django 3.2.5 on 2021-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_universehotness'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
