# Generated by Django 3.1.4 on 2021-01-29 09:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_auto_20210129_0703'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='universeconsolidated',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='universeconsolidated',
            name='consolidated_ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
