# Generated by Django 3.1.4 on 2021-07-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_universe_revenue_per_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='revenue_per_share',
        ),
    ]
