# Generated by Django 3.1.4 on 2021-01-29 09:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0006_auto_20210129_0907'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='universeconsolidated',
            managers=[
                ('ingestion_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
