# Generated by Django 3.1.4 on 2021-07-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0006_auto_20210712_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universeratingdetailhistory',
            old_name='tri_robust_scale',
            new_name='tri_quantile',
        ),
    ]
