# Generated by Django 3.2.5 on 2021-09-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0006_auto_20210909_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='etf_ticker',
            field=models.TextField(blank=True, null=True),
        ),
    ]
