# Generated by Django 3.2.5 on 2021-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0007_currency_etf_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='universerating',
            name='esg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universerating',
            name='fundamentals_extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universerating',
            name='fundamentals_momentum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='assets_1yr_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='assets_1yr_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='cash_ratio_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='cash_ratio_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='gross_margin_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='gross_margin_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='inv_turnover_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='inv_turnover_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='market_cap_usd_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='market_cap_usd_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='revenue_pred_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='revenue_pred_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r12_7_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r12_7_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r1_0_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r1_0_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r6_2_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='stock_return_r6_2_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='tax_less_pension_to_accu_depre_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='tax_less_pension_to_accu_depre_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='vol_0_30_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='vol_0_30_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='volume_minmax_currency_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratingdetailhistory',
            name='volume_minmax_industry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='fundamentals_extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='fundamentals_momentum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
