# Generated by Django 3.1.4 on 2021-01-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0007_auto_20210129_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
