# Generated by Django 3.1.4 on 2021-01-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0008_auto_20210129_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniverseConsolidated',
        ),
    ]
