# Generated by Django 3.2.5 on 2021-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0008_auto_20210924_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='universeratinghistory',
            name='ai_score2_unscaled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universeratinghistory',
            name='ai_score_unscaled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
