# Generated by Django 3.1.4 on 2021-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0008_remove_universe_yolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='yolo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
