# Generated by Django 3.1.4 on 2021-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0009_universe_yolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='yolo',
        ),
    ]
