# Generated by Django 3.2.5 on 2021-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0009_auto_20210924_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='ibes_currency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
