# Generated by Django 3.1.4 on 2021-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0010_universeconsolidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='consolidated_ticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='universeconsolidated',
            name='origin_ticker',
            field=models.CharField(max_length=50),
        ),
    ]
