# Generated by Django 3.2.5 on 2021-08-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0010_remove_universe_yolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='schi_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='tchi_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
