# Generated by Django 3.2.5 on 2021-09-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0010_universe_ibes_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universe',
            old_name='ibes_currency',
            new_name='currency_code_ibes',
        ),
        migrations.AddField(
            model_name='universe',
            name='currency_code_ws',
            field=models.TextField(blank=True, null=True),
        ),
    ]
