# Generated by Django 3.2.5 on 2021-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_auto_20210929_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPriceHistory',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_price_history',
                'managed': True,
            },
        ),
    ]
