# Generated by Django 3.1.4 on 2021-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_auto_20210129_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='universerating',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
