# Generated by Django 3.1.4 on 2021-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_universerating_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='ticker_symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
