# Generated by Django 3.2.5 on 2021-12-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_currencypricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universeratingdetailhistory',
            options={'managed': False},
        ),
    ]
