# Generated by Django 3.1.4 on 2021-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0014_universeconsolidated_has_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universeconsolidated',
            name='has_data',
            field=models.BooleanField(default=False),
        ),
    ]
