# Generated by Django 3.1.4 on 2021-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_auto_20210316_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='exchange_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
