# Generated by Django 3.1.4 on 2021-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='classic_schedule',
            new_name='backtest_schedule',
        ),
        migrations.AddField(
            model_name='currency',
            name='hanwha_close_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='hanwha_open_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
