# Generated by Django 3.1.4 on 2021-05-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0018_auto_20210506_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='hanwha_open_schedule',
            new_name='top_stock_schedule',
        ),
    ]
