# Generated by Django 3.1.4 on 2021-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0019_auto_20210506_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='index_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='index_ticker',
            field=models.TextField(blank=True, null=True),
        ),
    ]
