# Generated by Django 3.1.4 on 2021-05-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0020_auto_20210507_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField(default=False)),
                ('description', models.TextField(default=False)),
                ('last_updated', models.DateField(default=False)),
                ('date_source', models.DateField(default=False)),
                ('date_replace', models.DateField(default=False)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='special_cases_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'special_cases',
                'managed': True,
            },
        ),
    ]
