# Generated by Django 3.1.4 on 2021-05-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0021_specialcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcases',
            name='cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialcases',
            name='date_replace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialcases',
            name='date_source',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialcases',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialcases',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
