# Generated by Django 3.1.4 on 2021-05-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0022_auto_20210511_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_exchange_code', models.TextField(blank=True, null=True)),
                ('reference_exchange_code', models.TextField(blank=True, null=True)),
                ('source_id', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_code_source_id', to='universe.source')),
            ],
            options={
                'db_table': 'exchange_code',
                'managed': True,
            },
        ),
    ]
