# Generated by Django 3.1.4 on 2021-05-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0023_exchangecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeCode',
        ),
    ]
