# Generated by Django 3.1.4 on 2021-05-20 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0024_delete_exchangecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCode',
            fields=[
                ('exchange_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('exchange_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exchange_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeCodeReference',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('exchange_code_reference', models.TextField(blank=True, null=True)),
                ('exchange_code', models.ForeignKey(db_column='exchange_code', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_code_reference_exchange_code', to='universe.exchangecode')),
                ('source_id', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_code_reference_source_id', to='universe.source')),
            ],
            options={
                'db_table': 'exchange_code_reference',
                'managed': True,
            },
        ),
    ]
