# Generated by Django 3.1.4 on 2021-05-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0025_exchangecode_exchangecodereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecodereference',
            name='exchange_code',
        ),
        migrations.RemoveField(
            model_name='exchangecodereference',
            name='source_id',
        ),
        migrations.RenameField(
            model_name='universe',
            old_name='exchange_code',
            new_name='mic',
        ),
        migrations.DeleteModel(
            name='ExchangeCode',
        ),
        migrations.DeleteModel(
            name='ExchangeCodeReference',
        ),
    ]
