# Generated by Django 3.1.4 on 2021-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0026_auto_20210520_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMarket',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('mic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'exchange_market',
                'managed': True,
            },
        ),
    ]
