# Generated by Django 3.1.4 on 2021-05-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0027_exchangemarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemarket',
            name='currency_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange', to='universe.currency'),
        ),
    ]
