# Generated by Django 3.1.4 on 2021-05-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0028_exchangemarket_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemarket',
            name='currency_code',
            field=models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange', to='universe.currency'),
        ),
    ]
