# Generated by Django 3.1.4 on 2021-05-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0029_auto_20210520_0713'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exchangemarket',
            table='universe_exchange_market',
        ),
    ]
