# Generated by Django 3.1.4 on 2021-05-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0030_auto_20210521_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseRatingHistory',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('classic_vol', models.FloatField(blank=True, null=True)),
                ('fundamentals_quality', models.FloatField(blank=True, null=True)),
                ('fundamentals_value', models.FloatField(blank=True, null=True)),
                ('dlp_1m', models.FloatField(blank=True, null=True)),
                ('dlp_3m', models.FloatField(blank=True, null=True)),
                ('wts_rating', models.FloatField(blank=True, null=True)),
                ('wts_rating2', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='universe_rating_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'universe_rating_history',
                'managed': True,
            },
        ),
    ]
