# Generated by Django 3.1.4 on 2021-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0031_universeratinghistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='universe',
            index=models.Index(fields=['ticker_symbol', 'currency_code', 'mic'], name='universe_ticker__3a2a21_idx'),
        ),
    ]
