# Generated by Django 3.1.4 on 2021-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgbmpredfinaleps',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
