# Generated by Django 3.1.4 on 2021-04-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_value', '0002_auto_20210423_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgbmpredfinal',
            name='testing_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lgbmpredfinaleps',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lgbmscore',
            name='finish_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lgbmscore',
            name='testing_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
