Parameters:
  NetworkStackName:
    Description: Name of the base stack with all infra resources
    Type: String

Resources:
    RuleSSHec2:
        Type: AWS::EC2::SecurityGroup
        DeletionPolicy: Retain
        Properties:
            GroupName: only-ssh-sg
            GroupDescription: Limits security group only ssh traffic
            VpcId: 
                Fn::ImportValue:
                    Fn::Sub: "${NetworkStackName}-VPCID"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
    VpcSg:
        Type: AWS::EC2::SecurityGroup
        DeletionPolicy: Retain
        Properties:
            GroupName: db-sg
            GroupDescription: for db instance
            VpcId:
                Fn::ImportValue:
                    Fn::Sub: "${NetworkStackName}-VPCID"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 5432
                  ToPort: 5432
                  CidrIp: 0.0.0.0/0
    # PvsubnetDB:
    #     Type: AWS::RDS::DBSubnetGroup
    #     Properties: 
    #         DBSubnetGroupDescription: pvsubnet
    #         DBSubnetGroupName: pvdbsubnet
    #         SubnetIds: 
    #             Fn::ImportValue:
    #                 Fn::Sub: "${NetworkStackName}-PrivateSubnetID"
    
    BastionHost:
        Type: AWS::EC2::Instance
        DeletionPolicy: Retain
        Properties:
            KeyName: asklora-hk.pem
            ImageId: ami-077c694a31fa99701
            InstanceType: c5.xlarge
            SecurityGroupIds:
                - !Ref RuleSSHec2
            SubnetId:
                Fn::ImportValue:
                    Fn::Sub: "${NetworkStackName}-PublicSubnetID"
            UserData: !Base64 |
                #!/bin/bash -ex
                # put your script here
            Tags:
              - Key: Name
                Value: bastion
    
    
    rdsDBInstance:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Retain
        Properties:
            DBInstanceClass: db.t3.small
            AvailabilityZone: ap-east-1a
            DBName: postgres
            DBSecurityGroups: 
            - db-sg-group
            DBSubnetGroupName: pv-subnet-db
            Engine: postgres
            MasterUsername: postgres
            MasterUserPassword: askLORA2020$
            MultiAZ: false
            Port: 5432
            PubliclyAccessible: false
            VPCSecurityGroups:
                - !Ref VpcSg