# Generated by Django 3.1.4 on 2021-07-15 06:15

import core.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.user.models.usermanagerprofile)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(blank=True, choices=[('unverified', 'unverified'), ('verified', 'verified'), ('in waiting list', 'in waiting list'), ('approved', 'approved')], default='unverified', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_core',
            },
        ),
        migrations.CreateModel(
            name='Accountbalance',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('balance_uid', models.CharField(blank=True, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('currency_code', models.ForeignKey(db_column='currency_code', default='USD', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_currency', to='universe.currency')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_balance',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('side', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('transaction_detail', models.JSONField(blank=True, default=dict, null=True)),
                ('balance_uid', models.ForeignKey(db_column='balance_uid', on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction', to='user.accountbalance')),
            ],
            options={
                'db_table': 'user_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'username'], name='user_core_email_c85405_idx'),
        ),
    ]
