# Generated by Django 3.1.4 on 2021-01-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_currency', to='universe.currency'),
        ),
    ]
