# Generated by Django 3.1.4 on 2021-01-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_type',
            new_name='broker_account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='frac',
        ),
        migrations.RemoveField(
            model_name='user',
            name='over_18',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_notif',
        ),
    ]
