# Generated by Django 3.2.5 on 2021-08-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicalaccountbalance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalaccountbalance',
            table='user_account_history',
        ),
    ]
