# Generated by Django 3.1.4 on 2021-04-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
