# Generated by Django 3.2.5 on 2021-08-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_historicalaccountbalance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfitHistory',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(blank=True, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('daily_profit', models.FloatField(default=0)),
                ('daily_profit_pct', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_profit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profit_history',
            },
        ),
    ]
