# Generated by Django 3.1.4 on 2021-04-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='balance_id',
        ),
        migrations.RemoveField(
            model_name='userloghistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='Accountbalance',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.DeleteModel(
            name='UserLogHistory',
        ),
    ]
