# Generated by Django 3.1.4 on 2021-04-23 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        ('user', '0004_auto_20210416_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountbalance',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('balance_uid', models.CharField(blank=True, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_currency', to='universe.currency')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_balance',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('bot_transaction', models.CharField(blank=True, max_length=500, null=True)),
                ('balance_uid', models.ForeignKey(db_column='balance_uid', on_delete=django.db.models.deletion.CASCADE, related_name='account_trasaction', to='user.accountbalance')),
            ],
            options={
                'db_table': 'user_transaction',
            },
        ),
    ]
