# Generated by Django 3.1.4 on 2021-04-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210423_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='bot_transaction',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='description',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_detail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
