# Generated by Django 3.1.4 on 2021-04-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universe_exchange_code'),
        ('user', '0007_auto_20210423_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='currency',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='currency_code',
            field=models.ForeignKey(db_column='currency_code', default='USD', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_currency', to='universe.currency'),
        ),
    ]
