# Generated by Django 3.2.5 on 2021-09-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_total_invested_amount_userprofithistory_daily_invested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
