# Generated by Django 3.1.4 on 2021-06-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210423_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='balance_uid',
            field=models.ForeignKey(db_column='balance_uid', on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction', to='user.accountbalance'),
        ),
    ]
