# Generated by Django 3.1.4 on 2021-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210604_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_status',
            field=models.CharField(blank=True, choices=[('unverified', 'in waiting list'), ('verified', 'in waiting list'), ('in waiting list', 'in waiting list'), ('approved', 'approved')], default='unverified', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
