# Generated by Django 3.1.4 on 2021-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210616_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_status',
            field=models.CharField(blank=True, choices=[('unverified', 'unverified'), ('verified', 'verified'), ('in waiting list', 'in waiting list'), ('approved', 'approved')], default='unverified', max_length=255, null=True),
        ),
    ]
