# Generated by Django 3.1.4 on 2021-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210617_0347'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'username'], name='user_core_email_c85405_idx'),
        ),
    ]
