# Generated by Django 3.2.5 on 2021-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofithistory_total_profit_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofithistory',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
    ]
