# Generated by Django 3.2.5 on 2021-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofithistory_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofithistory',
            name='total_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofithistory',
            name='total_profit_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
