# Generated by Django 3.2.5 on 2021-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20211012_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_polyu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_polyu_af',
            field=models.BooleanField(default=False),
        ),
    ]
