# Generated by Django 3.2.5 on 2021-11-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20211021_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'season',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
            ],
            options={
                'db_table': 'segments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSegments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('segment_id', models.ForeignKey(db_column='segment_id', on_delete=django.db.models.deletion.CASCADE, related_name='segments_id', to='user.segments')),
            ],
            options={
                'db_table': 'user_segments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeasonHistory',
            fields=[
                ('uid', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('trading_day', models.DateField(blank=True, null=True)),
                ('total_profit', models.FloatField(blank=True, null=True)),
                ('total_profit_pct', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('season_id', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, related_name='season_history_season_id', to='user.season')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='season_history_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'season_history',
                'managed': True,
            },
        ),
    ]
