@startuml flow

title "Data flow of Droidv2"

!theme vibrant

skinparam Shadowing false
skinparam DefaultFontName Ubuntu
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Cron
box "Database"
database universe
database "data_dss, data_dsws" as base
database "master_ohlcvtr, master_tac" as updated
end box
participant "Data sources" as source

== Daily cron jobs triggered ==
Cron -> universe ++: Getting tickers to update

== Update data ==
universe -> source --++ : Getting updated prices from data sources
source --> base --++ : Resulting data is put into base tables

== Process data ==
base -> updated -- : Data from base tables are processed\nand input to the updated table

@enduml
