@startuml dsws

title "DSWS data flow"

!theme vibrant

skinparam Shadowing false
skinparam DefaultFontName Ubuntu
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam ConditionEndStyle diamond

start

package "datasource/dsws" {
    floating note: This file is used\nto get the data from\nDSWS
    :get_data_from_dss();

    :start_date\nend_date\nuniverse\nidentifier\n*field\nuse_ticker=True\ndividend=False\nsplit_number=40}

    :np.array_split()]
    note right
        Ticker is split into chunks with ""n""
        items defined in ""split_number""
    end note

    :DS.fetch()]

    :frame.reset_index()]
    note right
        The data reset by the ""DS.fetch()""
        bring their own index columns, so we
        remove those and create our own
    end note

    :data: Series[Dtype@concat] | list\nerror_universe: list/
}

stop

@enduml
