@startuml dsws

title "DSWS data flow"

!theme vibrant

skinparam shadowing false
skinparam defaultFontName Ubuntu
skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Data source" #LightBlue
participant DSWS
end box
box "Database"
participant data_dsws
end box

group ingestion/data_from_dsws
    == Getting data from DSWS ==

    group datasource/dsws
        create data
        rnote over DSWS, data
        Data is requested from DSWS within
        a time window, split into chunks
        end note

        DSWS -> data : resulting data
    end

    == resulting data is inserted\ninto table data_dsws ==

    group general/sql_output
        data -> data_dsws : upsert_data_to_database()
    end

end

@enduml
