@startuml quandl

title "Quandl data flow"

!theme vibrant

skinparam Shadowing false
skinparam DefaultFontName Ubuntu
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam ConditionEndStyle diamond

start

package "datasource/quandl" {
    floating note: This file is used\nto get the data from\nQuandl
    :read_quandl_csv();

    :ticker\nquandl_symbol\nstart_date\nend_date}

    :pd.read_csv()]
    note right
        The csv file is downloaded from quandl api
    end note

    :data = data.rename()]
    note right
        the date column is renamed into "trading_day"
    end note

    :uid_maker()]
    note right
        Create uids for the data_quandl
    end note

    :data: DataFrame/
}

stop

@enduml
