@startuml universe_populate

title "universe_populate routine flow"

!theme vibrant

skinparam Shadowing false
skinparam DefaultFontName Ubuntu
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam ConditionEndStyle diamond

start

:do_function("universe_populate");

:new data is input from ""universe_consolidated"" table]

note right
    this table gets its data from calling
    ""populate_universe_consolidated""
    ""_by_isin_sedol_from_dsws()""
    function
end note

:set all ""is_active"" fields on table ""universe"" to false]

:set them back to active on specific tickers]

:set some back to false on some others]

stop

@enduml
