# Generated by Django 3.1.4 on 2021-01-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0002_auto_20210108_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subinterval',
            fields=[
                ('subinterval', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('date_initial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subinterval',
            },
        ),
        migrations.CreateModel(
            name='WeeklyTopStock',
            fields=[
                ('uid', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('forward_date', models.DateField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('prediction_period', models.CharField(blank=True, max_length=200, null=True)),
                ('spot_price', models.FloatField(blank=True, null=True)),
                ('spot_tri', models.FloatField(blank=True, null=True)),
                ('forward_tri', models.FloatField(blank=True, null=True)),
                ('forward_return', models.FloatField(blank=True, null=True, verbose_name='absolute_return')),
                ('index_forward_return', models.FloatField(blank=True, null=True, verbose_name='ewportperfomance')),
                ('subinterval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdata_topstock', to='topstock.subinterval')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_top_stock', to='universe.universe')),
            ],
            options={
                'db_table': 'top_stock_weekly',
            },
        ),
        migrations.CreateModel(
            name='IndexPerformance',
            fields=[
                ('uid', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('types', models.CharField(blank=True, max_length=200, null=True)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('forward_date', models.DateField(blank=True, null=True)),
                ('index_spot_price', models.FloatField(blank=True, null=True)),
                ('index_forward_price', models.FloatField(blank=True, null=True)),
                ('index_forward_return', models.FloatField(blank=True, null=True)),
                ('wts_tri', models.FloatField(blank=True, null=True)),
                ('index_tri', models.FloatField(blank=True, null=True)),
                ('average_forward_return', models.FloatField(blank=True, null=True)),
                ('week_status', models.CharField(blank=True, max_length=200, null=True)),
                ('index_currency', models.ForeignKey(db_column='index_currency', on_delete=django.db.models.deletion.CASCADE, related_name='index_currency_performance', to='universe.currency')),
                ('subinterval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdata_performance', to='topstock.subinterval')),
            ],
            options={
                'db_table': 'top_stock_performance',
            },
        ),
    ]
