# Generated by Django 3.2.5 on 2021-08-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topstock', '0002_auto_20210801_0835'),
        ('topstock', '0002_auto_20210802_0142'),
    ]

    operations = [
    ]
