# Generated by Django 3.2.5 on 2021-08-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('topstock', '0002_auto_20210731_0610'),
        ('topstock', '0002_auto_20210813_0351'),
    ]

    operations = [
    ]
