# Generated by Django 3.1.4 on 2021-02-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topstock', '0003_topstockperformance_topstockweekly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopStockModelStock',
        ),
    ]
