# Generated by Django 3.1.4 on 2021-02-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_universerating_updated'),
        ('topstock', '0004_delete_topstockmodelstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStockModelStock',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data_period', models.TextField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('forward_date', models.DateField(blank=True, null=True)),
                ('spot_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('num_periods_to_predict', models.IntegerField(blank=True, null=True)),
                ('number_of_quantiles', models.IntegerField(blank=True, null=True)),
                ('predicted_quantile_1', models.IntegerField(blank=True, null=True)),
                ('signal_strength_1', models.FloatField(blank=True, null=True)),
                ('pc_number', models.TextField(blank=True, null=True)),
                ('currency_code', models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_stock_models_stock_currency_code', to='universe.currency')),
                ('model_filename', models.ForeignKey(blank=True, db_column='model_filename', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_stock_models_stock_model_filename', to='topstock.topstockmodel')),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_stock_models_stock_ticker', to='universe.universe')),
            ],
            options={
                'db_table': 'top_stock_models_stock',
            },
        ),
    ]
