# Generated by Django 3.1.4 on 2021-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topstock', '0005_topstockmodelstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('currency_code', models.CharField(max_length=5)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'top_stock_log',
                'ordering': ['year', 'week'],
            },
        ),
    ]
