---
- name: connect to worker Instance(s) 
  hosts: worker
  remote_user: ubuntu
  tasks:
    - name: copy yaml
      ansible.builtin.copy:
        src: /home/ubuntu/DROID_V2.1/deployment/compose/celery-worker.yaml
        dest: /home/ubuntu/swarm-celery.yaml
    - name: ecr docker get-authorization-token
      shell: "aws ecr get-login-password --region ap-east-1"
      register: ecr_command
      
    - set_fact:
        password: "{{ ecr_command.stdout }}"
    
    - debug: msg="{{password}}"
    
    - name: docker_repository - Log into ECR registry and force re-authorization
      docker_login:
        registry_url: "736885973837.dkr.ecr.ap-east-1.amazonaws.com"
        username: "AWS"
        password: "{{ password }}"
        reauthorize: yes
    - name: Stop Container
      command: docker-compose -p celery -f swarm-celery.yaml down
      args:
        chdir: /home/ubuntu
    - name: Clean docker system
      command: docker system prune -a -f
      args:
        chdir: /home/ubuntu
    - name: Clean docker image
      command: docker image prune -a -f
      args:
        chdir: /home/ubuntu
    - name: Run Container
      command: docker-compose -p celery -f swarm-celery.yaml up --build --force-recreate -d
      args:
        chdir: /home/ubuntu
