---

- name: connect to local pc
  hosts: local-pc
  remote_user: loratech
  tasks:
    - name: pull from git
      git:
        repo: https://redloratech:r3dpapermo0n@github.com/stepchoi/DROID_V2.1.git
        dest: /home/loratech/PycharmProjects/DROID_V2.1
        update: yes
        version: master
        force: yes