---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to bastion hosts
- name: connect to Instance(s) 
  hosts: instance
  remote_user: ubuntu
  tasks:
  # task is pulling from repo
    - name: pull from git
      git:
        repo: git@github.com:asklora/DROID_V2.1.git
        dest: /home/ubuntu/DROID_V2.1
        update: yes
        version: master
