# Generated by Django 3.1.4 on 2021-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210225_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='location',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
