name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"

    steps:
      - uses: actions/checkout@v2
      - name: Run instance update repo
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./deployment/ansible
          key: ${{secrets.BASTIONKEY}}
          inventory: |
            [instance]
            18.167.118.164
      - name: Run local update repo
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: local-playbook.yml
          directory: ./deployment/ansible
          key: ${{secrets.LOCALKEY}}
          inventory: |
            [local-pc]
            1.tcp.ap.ngrok.io ansible_port=20783
            1.tcp.ap.ngrok.io ansible_port=20782