name: Ansible auto update  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'dev-run')"

    steps:
      - uses: actions/checkout@v2
      - name: Run instance update
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # template task
          playbook: playbook.yml
          directory: ./deployment/ansible
          # using secrets variable on github to store .pem key for instance
          key: ${{secrets.BASTIONKEY}}
          # host address to manage
          inventory: |
            [instance]
            16.162.110.123