name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your SSH key
    - uses: actions/checkout@v2
    - run: 'echo "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAxD5iPbd1ITm545C011zXrYYnAEXK/S7wP6qOfT9uiQswuQv6
z9TdLIQxiDWGktn5Q+0+DvP5k7hD03X8zXaIMQJW6SbF2J0mfKiGztQ2WhJpElqn
kcvI6Wko/79+mtRb83UG7ca10haprEk837YBiBNs7mJT6VfW7aw5ygdgnfw3wR1M
8XyE+EAkIlFZOdN3a2Ac3zLRT298G80BSZCO0VVm5yrzKlp2MuaBnBDKAjz47dBn
iehA8J6Y93R2xa8QIXqigfn6RlqH0YnVh+M7Ori/fA5ING3HTZH4vXVNtBgCRaDK
e9ISmXs/N3uKUbZOm7Vw34SmehUER8cxe1uVRwIDAQABAoIBAH+IAxQUizwCZblr
qvpiTY9pJSNaN+Z9gIf/cQYYGN9atFktXdt+fBWX+xCHqGL64LCyFqhlCQZksz9S
5+0mYK9o085E8kIpLn/IjYMQChpS6JGS9F8dTf3R52D8s2wvIWp/3PbdMf/L1owu
NC81+pzR8vKgV+PGv9hJGm0eij1gLgq7aiOVIQz/mF5504hVoRcBFs6VNgKk/4g/
lLnJXg0u6tvwfU/LSwvLmkWwzT4E6bQCodN8mb5E2LYdee+kGrS0Rp6m3/KVzEOG
pkZWkm03UTTnbv7HLo7d2b6hbTMZil8wXQ1lvpboHfRFZSEHRE+Hmts7Sanl2LMX
gvd0tTECgYEA4v3r3bIQpEK9i7knXMIxD9+q2pR41zNZ2TNjGEy08CLOMf4YG0Im
fWhbyWUmjikSQJXe5SvbeMuZbvslUj4Ty8lMiRjhlcRw1ZIx7nwZ56sRpWC0/b9r
EHvPzQefMKVjKqUMexoQtyXJfAmUsRnPosgBup5h7HotUBhJx2xuERsCgYEA3VKH
qQeSzMbE7zG+Rck996s9WDilWCfS1M1ShbFvDcIOs69ix45TbWToSIar/gpSgFE7
u0n4pneFWC3G47oANdRbeQx+9RIKmCP9Hdi5wPuoBm0Xgl5G1SAjCYGF+oETUr+E
vZv+w362xS9AiIPKgjD9eWJQfMdMXoB9fG77e0UCgYBEje27Yfj2sxVt6niB4kBR
C/sc0rSAQgkDuSpXf2syD0D5BkWfjeX0AB2ggIUZcDwL93d+/TTmkY8AXqdR5F+0
L1KHIVWYFuEBD4s2/JISTq8gpEllTXd3Xf1PbdrdJUYC7iAL2b5soePtKzOWHTaB
cihbhVQLyIaA5yT5Lr07OwKBgE5G4To0NoR8jKx4sG4oNeWByAmKx1f9hcDD+brV
PYzlJKQClPI1cWZQeSMllnEcH3/Iu1KLYAkoXp4IWr6yS16+g7e1ZrWwstSKbfx/
aXtKxmu3a8gtJeo9GodDKyqlOjtbB0y0fo+QIn5tLurZiecwAoZK8mKfbnBCC5/V
9NXtAoGBAJbVDc/F2qzCnQgCbGDVRBUbj/aPpn0yreoGZargPcGBwQnmStBoPkHr
OyVBJakFzlwAoYf+QPgd0lH9Uuk6tf6AGObXbH+aMNtPlJQQ52my+oWt2nlyy7iX
8NSrISZqWtU1i3oZxQggBxfQ3WiwL57zxM8Y7C2DNbv3zHAvft7A
-----END RSA PRIVATE KEY-----" > asklora-hk.pem'
      shell: bash
      env:
        SSH_KEY: ${{secrets.BASTIONKEY}}
    - run: 'chmod 400 asklora-hk.pem'
      shell: bash
    - run: 'cat asklora-hk.pem'
      shell: bash
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: arillso/action.playbook@master
      with:
        playbook: deployment/ansible/playbook.yml
        inventory: deployment/ansible/inventory.yml