name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your SSH key
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "asklora-hk.pem"
        FILE_DATA: "${{secrets.BASTIONKEY}}"
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: arillso/action.playbook@master
      with:
        playbook: deployment/ansible/playbook.yml
        inventory: deployment/ansible/inventory.yml