name: Ansible auto update  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to ECR
      - run: echo "DROID"
        if: "contains(github.event.head_commit.message, 'ecr')"
      - run: docker build . -t droid -f deployment/batch/Dockerfile.celery
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-east-1
          image: droid:latest

      - name: Create test env
      - run: echo "env test"
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-east-1
          image: droid-test:latest
        id: ecr_env
        if: "contains(github.event.head_commit.message, 'build-test')"
      - run: docker build . -t droid-test -f deployment/container/Dockerfile.test