# name: CI build and test

# on:
#   push:
#     branches:
#       - dev
# jobs:
#   login:
#     runs-on: ubuntu-latest
#     outputs:
#       token: ${{ steps.ecr.outputs.token }}
#     steps:
#       - name: Get token to login to Amazon ECR
#         id: ecr
#         uses: PhutureCorp/ecr-login-token@v0.8.0
#         with:
#           registry: 736885973837.dkr.ecr.ap-east-1.amazonaws.com
#           username: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#   test:
#     needs: login
#     runs-on: ubuntu-latest
#     container:
#       image: 736885973837.dkr.ecr.ap-east-1.amazonaws.com/app-test-env:latest
#       credentials:
#         username: AWS
#         password: ${{ needs.login.outputs.token }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: check env
#         run: cat .env
#       - name: running test
#         run: pytest -s