name: CI build and test

on: [push]
jobs:
  login:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'testenv')"


    steps:
      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-east-1
      - run: echo ${{ steps.ecr.outputs.password }}
    outputs:
      output: "${{ steps.ecr.outputs.password }}"

  test:
    needs: login
    runs-on: ubuntu-latest
    container:
      image: 736885973837.dkr.ecr.ap-east-1.amazonaws.com/app-test-env:latest
      credentials:
        username: AWS
        password: echo "${{ needs.login.outputs.output }}"
    steps:
      - uses: actions/checkout@v2
      - name: running test
        run: ls -a